### ISSUE TITLE
Permission denied: '/var/log/supervisor/supervisord.log

### ISSUE THREAD

**Issue by abh** [docker-mailserver/docker-mailserver-helm#7]
My mail server pod isn't starting, it errors out with the message below. I realize it's likely a local configuration problem, but I thought I'd setup the namespace with an unrestricted PSP (and the helm chart comes with PSPs anyway).

```
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.1', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 365, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 375, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 78, in main
    info_messages)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1398, in make_logger
    stdout = self.nodaemon,
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log
```

**Comment by abh** [comment]
oh, no -- I think the defaults in `pod.dockermailserver.securityContext` is bad. I don't see how it can work with runAsUser 10001.

**Comment by funkypenguin** [comment]
You're right, this is not going to work. That was an addition to make kube-score happy, but it doesn't work on my end either. I'll roll it back.

**Comment by funkypenguin** [comment]
Latest version removes securityContext altogether, since I've not been able to get the container to "play nice" with any variations of securityContext :(
